/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// package bitmap.transformer;

import java.io.IOException;
public class App {

     public static void main(String[] args) throws IOException {
         System.out.println("Hello World");
      Bitmap Girl = new Bitmap();

  }
}