package bitmap.transformer;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        String inputFilePathToImage = "./app/src/main/resources/test.bmp";
        String outputFilePathToFolder = "./app/src/main/resources/NewImages";
        String edgeColor = "Edged";
        String convertToGrayScale="GrayScale";
        String negativeImage= "Negative";
        String reverseImageVertically="Vertical";
        String convertToGreens="Green";
        String convertImageToPinkBox="Pink";


        Bitmap Edged = new Bitmap(inputFilePathToImage, outputFilePathToFolder, edgeColor);
        Bitmap GrayScale = new Bitmap(inputFilePathToImage, outputFilePathToFolder, convertToGrayScale);
        Bitmap Negative = new Bitmap(inputFilePathToImage, outputFilePathToFolder, negativeImage);
        Bitmap Vertical = new Bitmap(inputFilePathToImage, outputFilePathToFolder, reverseImageVertically);
        Bitmap Green = new Bitmap(inputFilePathToImage, outputFilePathToFolder, convertToGreens);
        Bitmap Pink = new Bitmap(inputFilePathToImage, outputFilePathToFolder, convertImageToPinkBox);



        Edged.edgeColor();
        GrayScale.convertToGrayScale();
        Negative.negativeImage();
        Vertical.reverseImageVertically();
        Green.convertToGreens();
        Pink.convertImageToPinkBox();


        }
}
