/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;

public class Bitmap {

    private String originalphoto;
    private String newphoto;
    private String transformation;

    public Bitmap(String originalphoto, String newphoto, String transformation) {

        this.originalphoto = "./src/main/resources/"+ originalphoto + ".bmp";
        this.newphoto = "./src/main/resources/"+ newphoto + ".bmp";
        if (transformation.equals("convert")){
            convert();
        } else {
            System.out.println("The method you requested does not exist❌");
        }
    }

    public void copyfile(String src, String dest) throws IOException{
        File source = new File(src);
        File destination = new File(dest);
        Files.copy(source.toPath(), destination.toPath());
    }

    public void convert(){
        try {
            File input = new File(originalphoto);
            BufferedImage image = ImageIO.read(input);

            BufferedImage result = new BufferedImage(image.getWidth(), image.getHeight(), BufferedImage.TYPE_BYTE_BINARY);

            Graphics2D graphic = result.createGraphics();
            graphic.drawImage(image, 0, 0, Color.WHITE, null);
            graphic.dispose();

            File output = new File(newphoto);
            ImageIO.write(result, "bmp", output);

        } catch (IOException e){
            e.printStackTrace();
        }
    }

}